package de.htw.spaetiapp.util;

public enum ToastResponse {
    SPAETI_UPDATE_SUCCESSFUL, SPAETI_UPDATE_SERVER_UNSUCCESSFUL,SPAETI_UPDATE_REPO_UNSUCCESSFUL, SPAETI_ADD_SUCCESSFUL,
    SPAETI_ADD_REPO_UNSUCCESSFUL ,SPAETI_ADD_SERVER_UNSUCCESSFUL, SPAETI_DELETE_SUCCESSFUL, SPAETI_DELETE_REPO_UNSUCCESSFUL,
    SPAETI_DELETE_SERVER_UNSUCCESSFUL, INVALID_ADDRESS;
}
